FROM node:14.17.0

WORKDIR /usr/

COPY package*.json ./

RUN yarn install

COPY ./src/config ./src/config
COPY ./src/proto/student.proto ./src/proto/student.proto
COPY ./src/microservice/database ./src/microservice/database
COPY ./src/microservice/service/student.js ./src/microservice/service/student.js

EXPOSE 50053

CMD ["yarn", "start:micro:student"]