FROM node:14.17.0

WORKDIR /usr/

COPY package*.json ./

RUN yarn install --network-timeout 1000000

COPY ./src/config ./src/config
COPY ./src/proto ./src/proto
COPY ./src/restApi ./src/restApi

EXPOSE 3000

CMD ["yarn", "start:rest"]