CREATE TABLE IF NOT EXISTS student (
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) DEFAULT NULL,
  email VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS project (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  desc VARCHAR(50) DEFAULT NULL,
  createdAt TIMESTAMP(3) DEFAULT NULL,
  updatedAt TIMESTAMP(3) DEFAULT NULL,
  PRIMARY KEY (id)
);
